version: "3.9"
services:
  web:
    build: ./App
    ports:
      - "5000:5000"
    volumes:
      - sidecar:/sidecar
    command: sh -c "git clone https://github.com/vittorio-nardone/sidecar.git ; flask run"
  redis:
    image: "redis:alpine"
  refresh:
    build: ./Refresh
    command: sh -c "cd /sidecar ; git config pull.ff only ; watch -n 60 git pull"    
    volumes:
      - sidecar:/sidecar
volumes:
  sidecar:
